input {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
    topics => ["kafka-logs"]
    group_id => "logstash-diploma-v2"
    auto_offset_reset => "earliest"
    codec => "json"
    
    security_protocol => "SSL"
    ssl_truststore_type => "pkcs12"
    ssl_truststore_location => "/usr/share/logstash/config/certs/logstash-truststore.p12"
    ssl_truststore_password => "changeit"
    ssl_endpoint_identification_algorithm => ""
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_verification_mode => "none"
    index => "filebeat-%{+YYYY.MM.dd}"
    ilm_enabled => false
    manage_template => false
}
}
